# save this file as makefile.vars
# run this makefile using the following command
# make -f makefile.vars
ifeq "$(MYMC)" "Laptop"
	CC=gcc
endif

ifeq "$(MYMC)" "Aqua"
	CC=icc
endif

default: 
	@echo "Hello"
	@echo $(MYMC)
	@echo $(CC)
